name: Build & Deploy Banking App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and Deploy Banking App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '24'
          cache: 'maven'  # Cache Maven dependencies for faster builds

      - name: Unit Tests
        run: mvn -B test --file pom.xml
        continue-on-error: true  # Continue to show logs even if tests fail

      - name: Build the application
        run: mvn -B clean package --file pom.xml  # Combined clean and package

      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # Updated to latest version
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6  # Updated to latest version, consolidated build and push
        with:
          context: .
          file: Dockerfile  # Changed 'dockerfile' to 'file' for consistency with action docs
          push: ${{ github.event_name != 'pull_request' }}  # Only push on push events, not PRs
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/banking-application-using-spring-boot:latest  # Lowercase tag for convention